language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="f9f7a9f4-516b-4908-9ed7-dbe2b8b2c6cc"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - dan.kattsyn@gmail.com
    on_success: never # default: change
    on_failure: always # default: always